### ISSUE TITLE
install appium_console error

### ISSUE THREAD

**Issue by liuf1986** [appium/ruby_console#62] opened 2017-02-15 08:43 UTC
liufdeMac-mini:/ liuf$ gem install --no-rdoc --no-ri appium_console bond
Building native extensions.  This could take a while...
/Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/ext/builder.rb:76: warning: Insecure world writable dir /Users/Shared/Android in PATH, mode 040777
ERROR:  Error installing appium_console:
	ERROR: Failed to build gem native extension.

    current directory: /Users/liuf/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.7.0.1/ext/nokogiri
/Users/liuf/.rvm/rubies/ruby-2.3.0/bin/ruby -r ./siteconf20170215-8126-54dfkh.rb extconf.rb
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/liuf/.rvm/rubies/ruby-2.3.0/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
/Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- openssl (LoadError)
	from /Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/https.rb:23:in `<top (required)>'
	from /Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/liuf/.rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:3:in `<top (required)>'
	from /Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/liuf/.rvm/gems/ruby-2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2.rb:2:in `<top (required)>'
	from /Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/liuf/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from extconf.rb:460:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/liuf/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-16/2.3.0/nokogiri-1.7.0.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/liuf/.rvm/gems/ruby-2.3.0/gems/nokogiri-1.7.0.1 for inspection.
Results logged to /Users/liuf/.rvm/gems/ruby-2.3.0/extensions/x86_64-darwin-16/2.3.0/nokogiri-1.7.0.1/gem_make.out
Building native extensions.  This could take a while...
Successfully installed bond-0.5.1
1 gem installed

**Comment by KazuCocoa** [comment] 2017-02-15 13:45
This error was caused by nokogiri.
Could you check installation of nokogiri1.7.0.1?

**Comment by KazuCocoa** [comment] 2017-04-25 07:34
Close this issue since the cause is nokogiri.

**Closed by KazuCocoa** 2017-04-25 07:34 UTC
