### ISSUE TITLE
ARC - Dependencies

### ISSUE THREAD

**Issue by xsmaster** [appium/ruby_console#45] opened 2015-04-09 19:16 UTC
It seems the version of Pry is very out of date. Does anyone mind if we upgrade it? I was trying to cd into an object and it failed. :(

So I will see what I can do and have someone else review it.

**Comment by bootstraponline** [comment] 2015-04-09 22:53
I agree it should be updated. Update the gemspec to the new version on rubygems then see if anything breaks. If it's all set then a pull request can be merged.

**Comment by bootstraponline** [comment] 2015-04-09 23:10
dupe of https://github.com/appium/ruby_console/issues/40, let's track the issue there.

**Closed by bootstraponline** 2015-04-09 23:10 UTC

**Comment by bootstraponline** [comment] 2015-04-16 22:38
@xsmaster v1.0.4 [has been released to rubygems](https://rubygems.org/gems/appium_console)
